storm = ["Then comes the creak of cables and the cries of seamen",
         "Clouds the darkened heavens have drowned, and snatched the daylight from their eyes",
         "Black night broods on the waters",
         "All around from pole to pole the rattling peals resound",
         "Frequent flashes light the lurid air",
         "All nature, big with instant ruin, frowned destruction",
         "A gust of the shrill north strikes full on the sail and raises the waves up to heaven",
         "The oars are snapped",
         "The prow swings away and gives her side to the waves",
         "Down in a heap comes a broken mountain of water",
         "The yawning billow shows ground amid the surge, where the sea churns with sand",
         "They hang on the wave's ridge",
         "The south wind catches and hurls a ship on hidden rocks", 
         "Rocks amid the waves, a vast reef banking the sea",
         "The east wind forces a ship from the deep into shallows and quicksands",
         "Piteous to see, it dashes on shoals and girdles with a sandbank",
         "Before their eyes a vast sea descending strikes astern",
         "The helmsman is dashed away and rolled forward headlong",
         "As she lies the billow sends her spinning thrice round with it, and engulfs her in the swift whirl",
         "Scattered swimmers appear in the vast eddy; armour of men, timbers and treasure amid the water"]

walking=["He set out from {from} amidst a throng travelling the same way",
         "He left the city early, before the rising of the sun",
         "Now the road is quieter",
         "Above the roads are ruins, among which is a cave sacred to Asclepius",
         "A caravan from {destination} passed by",
         "They pass a pillar on the right surmounted by a stone urn",
         "As they go up from {from}, they see the ruined walls",
         "Along the road are graves, and a cenotaph",
         "Not far from the road is a grave, on which is mounted a soldier standing by a horse. Who it is I do not know, but both horse and soldier were carved by Praxiteles",
         "On the road from {from} to {destination} there is a village, in which there is a temple and grove",
         "Here is an ancient sanctuary common to all the gods, and around it is a grove containing springs",
         "There is a fountain of cold water springing from the rock",
         "By the road is a salt spring",
         "He passes another milestone",
         "The sun beats down.",
         "A cloud passes in front of the sun",
         "His shoes are covered in dust from the road"]

travel=["The journey is more tiring than you might expect",
        "He presses onward",
        "No backward glances for the city left behind",
        "The sun beats down",
        "A cloud passes in front of the sun",
        "A breeze from an unexpected quarter cools the air",
        "The countryside is quieter than the city",
        "Birds sing their greetings"]