storm = ["Then comes the creak of cables and the cries of seamen",
         "Clouds the darkened heavens have drowned, and snatched the daylight from their eyes",
         "Black night broods on the waters",
         "All around from pole to pole the rattling peals resound",
         "Frequent flashes light the lurid air",
         "All nature, big with instant ruin, frowned destruction",
         "A gust of the shrill north strikes full on the sail and raises the waves up to heaven",
         "The oars are snapped",
         "The prow swings away and gives her side to the waves",
         "Down in a heap comes a broken mountain of water",
         "The yawning billow shows ground amid the surge, where the sea churns with sand",
         "They hang on the wave's ridge",
         "The south wind catches and hurls a ship on hidden rocks", 
         "Rocks amid the waves, a vast reef banking the sea",
         "The east wind forces a ship from the deep into shallows and quicksands",
         "Piteous to see, it dashes on shoals and girdles with a sandbank",
         "Before their eyes a vast sea descending strikes astern",
         "The helmsman is dashed away and rolled forward headlong",
         "As she lies the billow sends her spinning thrice round with it, and engulfs her in the swift whirl",
         "Scattered swimmers appear in the vast eddy; armour of men, timbers and treasure amid the water"]
