storm = ["Straightway the winds upturn the main, and great seas rise",
         "They are tossed asunder over the dreary gulf",
         "Stormclouds enwrap the day, and rainy gloom blots out the sky",
         "Out of the clouds bursts fire fast upon fire",
         "Driven from our course, we go wandering on the blind waves",
         "The navigator professes he cannot tell day from night on the sky, nor remember the way amid the waters",
         "Dubious days of blind darkness we wander on the deep, nights without a star"]

wreck = ["Then comes the creak of cables and the cries of seamen",
         "Clouds the darkened heavens have drowned, and snatched the daylight from their eyes",
         "Black night broods on the waters",
         "All around from pole to pole the rattling peals resound",
         "Frequent flashes light the lurid air",
         "All nature, big with instant ruin, frowned destruction",
         "A gust of the shrill north strikes full on the sail and raises the waves up to heaven",
         "Even as he cried, the hurricane from the North struck with a roar against the sail"
         "The shattered oars start forth",
         "Up leaped the waves to heaven",
         "The oars are snapped",
         "The prow swings away and gives her side to the waves",
         "Round swings the prow, and lets the waters sweep the broadside",
         "Down in a heap comes a broken mountain of water",
         "The yawning billow shows ground amid the surge, where the sea churns with sand",
         "They hang on the wave's ridge",
         "Onward comes a mountain heap of billows, gaunt, abrupt",
         "They are horsed astride a surge's crest, rocking pendent over the deep",
         "They are in the wave's huge hollow",
         "Yawning wide, the wave lays bare the ground below",
         "Dark swells the sandy tide",
         "The south wind catches and hurls a ship on hidden rocks", 
         "Rocks amid the waves, a vast reef banking the sea",
         "The east wind forces a ship from the deep into shallows and quicksands",
         "Piteous to see, it dashes on shoals and girdles with a sandbank",
         "Before their eyes a vast sea descending strikes astern",
         "The helmsman is dashed away and rolled forward headlong",
         "As she lies the billow sends her spinning thrice round with it, and engulfs her in the swift whirl",
         "Scattered swimmers appear in the vast eddy; armour of men, timbers and treasure amid the water",
         "Each loosened side through many a gaping seam lets in the baleful tide"
         ]

storm_end = ["Then was land at last seen to rise, discovering distant hills and sending up wreaths of smoke",
             "The sails drop; they swing back to the oars",
             "Without delay the sailors strongly toss up the foam",
             "They sweep through the green water"]

wreck_landing = ["In a far retreat there lies a haven",
                 "Within a long recess there lies a bay: an island shades it from the rolling sea and forms a port secure for ships to ride",
                 "Towards the deep doth stand an island, on whose jutting headlands beat the broken billows, shivered into sleet",
                 "Broke by the jutting land, on either side, in double streams the briny waters glide",
                 "Two towering crags, twin giants, guard the cove, and threat the skies",
                 "Betwixt two rows of rocks a sylvan scene appears above, and groves for ever green",
                 "The waters at their feet sleep hushed, and, like a curtain, frowns above, mixt with the glancing green, the darkness of the grove",
                 "Beneath a precipice that fronts the wave, with limpid springs inside, and many a seat of living marble, lies a sheltered cave",
                 "A grotto is formed beneath, with mossy seats, to rest the Nereids, and exclude the heats",
                 "Down through the crannies of the living walls the crystal streams descend in murmuring falls",
                 "No haulsers need to bind the vessels here. Nor bearded anchors; for no storms they fear",
                 "Ships within this happy harbor meet, the thin remainders of the scattered fleet",
                 "The sailors, worn with toils, and spent with woes, leap on the welcome land, and seek their wished-for repose",
                 "Glad at length to greet the welcome earth, the sailors leap to land",
                 "They lay their weary limbs still dripping on the sand"]

sailing_begin=["Having won favorable omens, the they put out to sea from {from} for {destination}"]

sailing=["They spread their sails and ran over the waste sea in their hollow wood",
         "The ship held the high seas, no land yet appearing",
         "The sky all round them and all round them the deep",
         "A dusky shower drew up overhead carrying night and tempest",
         "The wave shuddered and gloomed",
         "The breezes woo the sails, and the canvas blows out to the swelling south"
         ]

misc = ["This place likewise he abandoned",
        "And now a day and another day hath sped",
        "With these words I accost the prophet, and thus make request:"]

walking=["He had set out from {from} amidst a throng travelling the same way",
         "He left the city early, before the rising of the sun",
         "Now the road is quieter",
         "Above the roads are ruins, among which is a cave sacred to Asclepius",
         "A caravan from {destination} passed by",
         "They pass a pillar on the right surmounted by a stone urn",
         "As they go up from {from}, they see the ruined walls",
         "Along the road are graves, and a cenotaph",
         "Not far from the road is a grave, on which is mounted a soldier standing by a horse. Who it is I do not know, but both horse and soldier were carved by Praxiteles",
         "On the road from {from} to {destination} there is a village, in which there is a temple and grove",
         "Here is an ancient sanctuary common to all the gods, and around it is a grove containing springs",
         "There is a fountain of cold water springing from the rock",
         "By the road is a salt spring",
         "He passes another milestone",
         "The sun beats down",
         "A cloud passes in front of the sun",
         "His shoes are covered in dust from the road",
         "An oxcart passes, loaded with grain",
         "Next to the straight road that leads to {destination}, there is visible a sculpted tomb",
         "Workers are raising the level of the road",
         "The road narrows here, an orchard wall encroaching on it",
         "Water has washed out the road, making for slow going",
         "This is a smooth road, by which many wagons were bringing wood to {destination}",
         "A grove of Minerva is hard by the road, a grove of poplar trees",
         "There a spring wells up, and around about it is a meadow"]

travel=["The journey is more tiring than you might expect",
        "He presses onward",
        "No backward glances for the city left behind",
        "The sun beats down",
        "A cloud passes in front of the sun",
        "A breeze from an unexpected quarter cools the air",
        "The countryside is quieter than the city",
        "Birds sing their greetings"]

# Hom. Od. 6.251
harbor=["The harbor of {destination} came into view over the horizon",
        "A fair harbor lies on either side of the city and the entrance is narrow",
        "They beheld the harbor of {destination} with gladness",
        "Curved ships are drawn up along the road",
        "They all have stations for their ships, each man one for himself",
        "There, too, is their place of assembly about the fair temple of Poseidon, fitted with huge stones set deep in the earth",
        "Here the men are busied with the tackle of their black ships, with cables and sails", 
        "Here they shape the thin oar-blades",
        "For they care not for bow or quiver, but for masts and oars of ships",
        "They care for the shapely ships, rejoicing in that which they cross over the grey sea"]

inscriptions = ["On a pillar was written: {inscription}. He contemplated it",
                "By the gate of {destination}, these words were carved: {inscription}",
                "Virgil saw this on a roadside tomb: {inscription}",
                "Wondering if it was related to his journey, he read the words that were carved there: {inscription}",
                "There was written there these words: {inscription}",
                "They passed by an inscription that read: {inscription}",
                "{inscription} was carved into the stone",
                "{inscription}: he pondered the sight of this inscription",
                "At that place is inscribed: \"{inscription}\""]